// Emoji de banderas por nombre de equipo.
// Cubre tanto nombres en español (DB) como en inglés (API /api/live).

const FLAG_MAP = {
  // ── Español (nombres en DB) ──────────────────────────────────────────
  'Algeria':        '🇩🇿',  // fallback inglés por si llega así
  'Argelia':        '🇩🇿',
  'Arabia Saudita': '🇸🇦',
  'Argentina':      '🇦🇷',
  'Austria':        '🇦🇹',
  'Bélgica':        '🇧🇪',
  'Cabo Verde':     '🇨🇻',
  'Colombia':       '🇨🇴',
  'Croacia':        '🇭🇷',
  'Curaçao':        '🇨🇼',
  'Ecuador':        '🇪🇨',
  'España':         '🇪🇸',
  'Francia':        '🇫🇷',
  'Ghana':          '🇬🇭',
  'Inglaterra':     '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
  'Irak':           '🇮🇶',
  'Irán':           '🇮🇷',
  'Jordania':       '🇯🇴',
  'México':         '🇲🇽',
  'Noruega':        '🇳🇴',
  'Panamá':         '🇵🇦',
  'Portugal':       '🇵🇹',
  'RD Congo':       '🇨🇩',
  'Senegal':        '🇸🇳',
  'Uruguay':        '🇺🇾',
  'Uzbekistán':     '🇺🇿',
  // ── Inglés (nombres de /api/live) ───────────────────────────────────
  'Algeria':        '🇩🇿',
  'Australia':      '🇦🇺',
  'Belgium':        '🇧🇪',
  'Brazil':         '🇧🇷',
  'Canada':         '🇨🇦',
  'Cape Verde':     '🇨🇻',
  'Chile':          '🇨🇱',
  'Croatia':        '🇭🇷',
  'Denmark':        '🇩🇰',
  'DR Congo':       '🇨🇩',
  'England':        '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
  'France':         '🇫🇷',
  'Germany':        '🇩🇪',
  'Iraq':           '🇮🇶',
  'Iran':           '🇮🇷',
  'Japan':          '🇯🇵',
  'Jordan':         '🇯🇴',
  'Mexico':         '🇲🇽',
  'Morocco':        '🇲🇦',
  'Netherlands':    '🇳🇱',
  'Norway':         '🇳🇴',
  'Panama':         '🇵🇦',
  'Poland':         '🇵🇱',
  'Saudi Arabia':   '🇸🇦',
  'Serbia':         '🇷🇸',
  'South Korea':    '🇰🇷',
  'Spain':          '🇪🇸',
  'Switzerland':    '🇨🇭',
  'United States':  '🇺🇸',
  'USA':            '🇺🇸',
  'Uzbekistan':     '🇺🇿',
}

export const flag = (name) => FLAG_MAP[name] ?? '🏳️'
