// Códigos ISO 3166-1 alpha-2 por nombre de equipo.
// Cubre nombres en español (DB) y en inglés (/api/live).
// Devuelve el código en minúsculas listo para usar como clase CSS de flag-icons:
//   <span className={`fi fi-${flagCode(name)}`} />

const ISO_MAP = {
  // ── Español (nombres en DB) ──────────────────────────────────────────
  'Argelia':        'dz',
  'Arabia Saudita': 'sa',
  'Argentina':      'ar',
  'Austria':        'at',
  'Bélgica':        'be',
  'Cabo Verde':     'cv',
  'Colombia':       'co',
  'Croacia':        'hr',
  'Curaçao':        'cw',
  'Ecuador':        'ec',
  'España':         'es',
  'Francia':        'fr',
  'Ghana':          'gh',
  'Inglaterra':     'gb-eng',  // Cruz de San Jorge, no Union Jack
  'Irak':           'iq',
  'Irán':           'ir',
  'Jordania':       'jo',
  'México':         'mx',
  'Noruega':        'no',
  'Panamá':         'pa',
  'Portugal':       'pt',
  'RD Congo':       'cd',
  'Senegal':        'sn',
  'Uruguay':        'uy',
  'Uzbekistán':     'uz',
  // ── Inglés (nombres de /api/live) ───────────────────────────────────
  'Algeria':        'dz',
  'Australia':      'au',
  'Belgium':        'be',
  'Brazil':         'br',
  'Canada':         'ca',
  'Cape Verde':     'cv',
  'Chile':          'cl',
  'Colombia':       'co',
  'Croatia':        'hr',
  'Denmark':        'dk',
  'DR Congo':       'cd',
  'Ecuador':        'ec',
  'England':        'gb-eng',
  'France':         'fr',
  'Germany':        'de',
  'Ghana':          'gh',
  'Iraq':           'iq',
  'Iran':           'ir',
  'Japan':          'jp',
  'Jordan':         'jo',
  'Mexico':         'mx',
  'Morocco':        'ma',
  'Netherlands':    'nl',
  'Norway':         'no',
  'Panama':         'pa',
  'Poland':         'pl',
  'Portugal':       'pt',
  'Saudi Arabia':   'sa',
  'Senegal':        'sn',
  'Serbia':         'rs',
  'South Korea':    'kr',
  'Spain':          'es',
  'Switzerland':    'ch',
  'United States':  'us',
  'USA':            'us',
  'Uruguay':        'uy',
  'Uzbekistan':     'uz',
}

// Devuelve el código ISO del equipo (ej. 'es', 'sa', 'gb-eng').
// Retorna null si el equipo no está mapeado — el caller debe manejar el fallback.
export const flagCode = (name) => ISO_MAP[name] ?? null
